user = 's1997319'
filename = '/data/doina/UCSD-Amazon-Data/meta_Electronics.json.gz'
reviewsfile = '/data/doina/UCSD-Amazon-Data/reviews_Electronics.json.gz'
reviewsfilefarm = 'file:///home/' + user + '/reviews_Electronics.json.gz'
appleStockFile = "file:///home/" + user + "/aapl-apple-historicalStock.csv"
hpStockFile = "file:///home/" + user + "/hp-historicalStock.csv"
microsoftStockFile = "file:///home/" + user + "/msft-microsoft-historicalStock.csv"
Jan2013 = 1356998400
Jun2013 = 1370044800
Dez2014 = 1420070399